service: serverless-single-page-app

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1

functions:
  hello:
    handler: src/handler.hello

plugins:
  - serverless-plugin-typescript
