service: serverless-single-page-app

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1

functions:
  hello:
    handler: src/functions/handler.hello

custom:
  client:
    bucketName: serverless-single-page-app-assets

plugins:
  - serverless-plugin-typescript
  - serverless-client-s3
