service: serverless-single-page-app

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1

functions:
  checkAnswer:
    handler: src/functions/checkAnswer.process
    events:
      - http:
          path: /checkAnswer
          method: post

custom:
  client:
    bucketName: serverless-single-page-app-assets

plugins:
  - serverless-plugin-typescript
  - serverless-client-s3
